<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GrabacionRecorrido', 'doctrine');

/**
 * BaseGrabacionRecorrido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_sala
 * @property string $ruta_sonido
 * @property Sala $Sala
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method integer            getIdSala()      Returns the current record's "id_sala" value
 * @method string             getRutaSonido()  Returns the current record's "ruta_sonido" value
 * @method Sala               getSala()        Returns the current record's "Sala" value
 * @method GrabacionRecorrido setId()          Sets the current record's "id" value
 * @method GrabacionRecorrido setIdSala()      Sets the current record's "id_sala" value
 * @method GrabacionRecorrido setRutaSonido()  Sets the current record's "ruta_sonido" value
 * @method GrabacionRecorrido setSala()        Sets the current record's "Sala" value
 * 
 * @package    mantenedor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrabacionRecorrido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grabacion_recorrido');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'grabacion_recorrido_id',
             'length' => 4,
             ));
        $this->hasColumn('id_sala', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ruta_sonido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sala', array(
             'local' => 'id_sala',
             'foreign' => 'id'));
    }
}