<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Sala', 'doctrine');

/**
 * BaseSala
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $sala_numero
 * @property integer $numero_panoramicas
 * @property string $ruta_imagen_miniatura
 * @property integer $id_piso
 * @property integer $cord_x
 * @property integer $cord_y
 * @property integer $numero_panoramica_principal
 * @property boolean $estado
 * @property Piso $Piso
 * @property Doctrine_Collection $DetalleRecorrido
 * @property Doctrine_Collection $GrabacionRecorrido
 * @property Doctrine_Collection $Panoramica
 * 
 * @method integer             getId()                          Returns the current record's "id" value
 * @method string              getNombre()                      Returns the current record's "nombre" value
 * @method integer             getSalaNumero()                  Returns the current record's "sala_numero" value
 * @method integer             getNumeroPanoramicas()           Returns the current record's "numero_panoramicas" value
 * @method string              getRutaImagenMiniatura()         Returns the current record's "ruta_imagen_miniatura" value
 * @method integer             getIdPiso()                      Returns the current record's "id_piso" value
 * @method integer             getCordX()                       Returns the current record's "cord_x" value
 * @method integer             getCordY()                       Returns the current record's "cord_y" value
 * @method integer             getNumeroPanoramicaPrincipal()   Returns the current record's "numero_panoramica_principal" value
 * @method boolean             getEstado()                      Returns the current record's "estado" value
 * @method Piso                getPiso()                        Returns the current record's "Piso" value
 * @method Doctrine_Collection getDetalleRecorrido()            Returns the current record's "DetalleRecorrido" collection
 * @method Doctrine_Collection getGrabacionRecorrido()          Returns the current record's "GrabacionRecorrido" collection
 * @method Doctrine_Collection getPanoramica()                  Returns the current record's "Panoramica" collection
 * @method Sala                setId()                          Sets the current record's "id" value
 * @method Sala                setNombre()                      Sets the current record's "nombre" value
 * @method Sala                setSalaNumero()                  Sets the current record's "sala_numero" value
 * @method Sala                setNumeroPanoramicas()           Sets the current record's "numero_panoramicas" value
 * @method Sala                setRutaImagenMiniatura()         Sets the current record's "ruta_imagen_miniatura" value
 * @method Sala                setIdPiso()                      Sets the current record's "id_piso" value
 * @method Sala                setCordX()                       Sets the current record's "cord_x" value
 * @method Sala                setCordY()                       Sets the current record's "cord_y" value
 * @method Sala                setNumeroPanoramicaPrincipal()   Sets the current record's "numero_panoramica_principal" value
 * @method Sala                setEstado()                      Sets the current record's "estado" value
 * @method Sala                setPiso()                        Sets the current record's "Piso" value
 * @method Sala                setDetalleRecorrido()            Sets the current record's "DetalleRecorrido" collection
 * @method Sala                setGrabacionRecorrido()          Sets the current record's "GrabacionRecorrido" collection
 * @method Sala                setPanoramica()                  Sets the current record's "Panoramica" collection
 * 
 * @package    mantenedor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSala extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sala');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'sala_id',
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('sala_numero', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_panoramicas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => '0',
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ruta_imagen_miniatura', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('id_piso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cord_x', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('cord_y', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('numero_panoramica_principal', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => 'true',
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Piso', array(
             'local' => 'id_piso',
             'foreign' => 'numero_piso'));

        $this->hasMany('DetalleRecorrido', array(
             'local' => 'id',
             'foreign' => 'id_sala'));

        $this->hasMany('GrabacionRecorrido', array(
             'local' => 'id',
             'foreign' => 'id_sala'));

        $this->hasMany('Panoramica', array(
             'local' => 'id',
             'foreign' => 'id_sala'));
    }
}