<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Panoramica', 'doctrine');

/**
 * BasePanoramica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_sala
 * @property string $descripcion
 * @property string $ruta_imagen
 * @property integer $numero_orden
 * @property string $ruta_imagen_miniatura
 * @property boolean $estado
 * @property Sala $Sala
 * @property Doctrine_Collection $Exposicion
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getIdSala()                Returns the current record's "id_sala" value
 * @method string              getDescripcion()           Returns the current record's "descripcion" value
 * @method string              getRutaImagen()            Returns the current record's "ruta_imagen" value
 * @method integer             getNumeroOrden()           Returns the current record's "numero_orden" value
 * @method string              getRutaImagenMiniatura()   Returns the current record's "ruta_imagen_miniatura" value
 * @method boolean             getEstado()                Returns the current record's "estado" value
 * @method Sala                getSala()                  Returns the current record's "Sala" value
 * @method Doctrine_Collection getExposicion()            Returns the current record's "Exposicion" collection
 * @method Panoramica          setId()                    Sets the current record's "id" value
 * @method Panoramica          setIdSala()                Sets the current record's "id_sala" value
 * @method Panoramica          setDescripcion()           Sets the current record's "descripcion" value
 * @method Panoramica          setRutaImagen()            Sets the current record's "ruta_imagen" value
 * @method Panoramica          setNumeroOrden()           Sets the current record's "numero_orden" value
 * @method Panoramica          setRutaImagenMiniatura()   Sets the current record's "ruta_imagen_miniatura" value
 * @method Panoramica          setEstado()                Sets the current record's "estado" value
 * @method Panoramica          setSala()                  Sets the current record's "Sala" value
 * @method Panoramica          setExposicion()            Sets the current record's "Exposicion" collection
 * 
 * @package    mantenedor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePanoramica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('panoramica');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'panoramica_id',
             'length' => 4,
             ));
        $this->hasColumn('id_sala', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('ruta_imagen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('numero_orden', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ruta_imagen_miniatura', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => 'true',
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Sala', array(
             'local' => 'id_sala',
             'foreign' => 'id'));

        $this->hasMany('Exposicion', array(
             'local' => 'id',
             'foreign' => 'id_panoramica'));
    }
}