<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Piso', 'doctrine');

/**
 * BasePiso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $numero_piso
 * @property string $ruta_imagen
 * @property boolean $estado
 * @property Doctrine_Collection $Sala
 * 
 * @method integer             getNumeroPiso()  Returns the current record's "numero_piso" value
 * @method string              getRutaImagen()  Returns the current record's "ruta_imagen" value
 * @method boolean             getEstado()      Returns the current record's "estado" value
 * @method Doctrine_Collection getSala()        Returns the current record's "Sala" collection
 * @method Piso                setNumeroPiso()  Sets the current record's "numero_piso" value
 * @method Piso                setRutaImagen()  Sets the current record's "ruta_imagen" value
 * @method Piso                setEstado()      Sets the current record's "estado" value
 * @method Piso                setSala()        Sets the current record's "Sala" collection
 * 
 * @package    mantenedor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePiso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('piso');
        $this->hasColumn('numero_piso', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('ruta_imagen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('estado', 'boolean', 1, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'default' => 'true',
             'primary' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Sala', array(
             'local' => 'numero_piso',
             'foreign' => 'id_piso'));
    }
}