<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ExposicionSonido', 'doctrine');

/**
 * BaseExposicionSonido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_exposicion
 * @property string $ruta_sonido
 * @property Exposicion $Exposicion
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getIdExposicion()  Returns the current record's "id_exposicion" value
 * @method string           getRutaSonido()    Returns the current record's "ruta_sonido" value
 * @method Exposicion       getExposicion()    Returns the current record's "Exposicion" value
 * @method ExposicionSonido setId()            Sets the current record's "id" value
 * @method ExposicionSonido setIdExposicion()  Sets the current record's "id_exposicion" value
 * @method ExposicionSonido setRutaSonido()    Sets the current record's "ruta_sonido" value
 * @method ExposicionSonido setExposicion()    Sets the current record's "Exposicion" value
 * 
 * @package    mantenedor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExposicionSonido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exposicion_sonido');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'exposicion_sonido_id',
             'length' => 4,
             ));
        $this->hasColumn('id_exposicion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => true,
             'primary' => false,
             'length' => 4,
             ));
        $this->hasColumn('ruta_sonido', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'notnull' => false,
             'primary' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Exposicion', array(
             'local' => 'id_exposicion',
             'foreign' => 'id'));
    }
}