<?php

/**
 * DetalleRecorridoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleRecorridoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleRecorridoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetalleRecorrido');
    }
}