<?php

/**
 * ExposicionImagenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExposicionImagenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExposicionImagenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExposicionImagen');
    }
}