<?php

/**
 * ExposicionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExposicionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExposicionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Exposicion');
    }
    
    
}