<?php

/**
 * GrabacionRecorridoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrabacionRecorridoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrabacionRecorridoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrabacionRecorrido');
    }
}