<?php

/**
 * Panoramica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mantenedor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Panoramica extends BasePanoramica
{
  function __toString(){
    return $this->getDescripcion();
  }
  
  public function cambiarEstadoEnCascada($estado){
    
    foreach($this->getExposicion() as $exposicion){
      $exposicion->setEstado($estado);
      $exposicion->save();
    }
  }

}