<?php

/**
 * PanoramicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PanoramicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PanoramicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Panoramica');
    }
}