<?php

/**
 * PisoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PisoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PisoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Piso');
    }
    
    public function getSalas($num_piso){
      $q = Doctrine_query::create()
        ->from('Sala s')
        ->where('s.id_piso = ?', $num_piso)
        ->orderBy('s.sala_numero ASC')
        ->execute();
      
      return $q;
    }
}