<?php

/**
 * Piso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mantenedor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Piso extends BasePiso
{
  function __toString(){
    return "".$this->getNumeroPiso();
  }
  
  public function getSalas(){
    return Doctrine::getTable('Piso')->getSalas($this->getNumeroPiso());
  }
  
  public function cambiarEstadoEnCascada($estado){

    foreach($this->getSala() as $sala){
      $sala->setEstado($estado);
      $sala->save();
      foreach($sala->getPanoramica() as $panoramica){
        $panoramica->setEstado($estado);
        $panoramica->save();
        foreach($panoramica->getExposicion() as $exposicion){
          $exposicion->setEstado($estado);
          $exposicion->save();
        }
      }
    }
  }
  
  public function validarEstadoPiso(){
    $salas = $this->getSala();
    $bandera = false;
    if(count($salas) !=0){
      foreach($salas as $sala){
        if($sala->getEstado){
          $bandera =true;
        }
      }
    }
    $this->setEstado($bandera);
  }
}