<?php

/**
 * RecorridoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecorridoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecorridoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Recorrido');
    }
    
    public function getDetallesRecorridos($id_recorrido){
      $q = Doctrine_query::create()
        ->from('DetalleRecorrido dr')
        ->where('dr.id_recorrido = ?', $id_recorrido)
        ->orderBy('dr.orden ASC')
        ->execute();
      
      return $q;
    }
    
    public function getRecorridosDesactivados(){
      $q = Doctrine_query::create()
        ->from('Recorrido r')
        ->where('r.estado = ?',false)
        ->execute();
        
        return $q;
    }
}