<?php

/**
 * SalaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sala');
    }
    
    public function getPanoramicasDeSala($id_sala){
      $q = Doctrine_query::create()
        ->from('Panoramica p')
        ->where('p.id_sala = ?', $id_sala)
        ->orderBy('p.numero_orden ASC')
        ->execute();
      
      return $q;
    }
    
    public function getExposicionesDeSala($id_sala){
      /*
      $q = Doctrine_query::create()
      ->select('e.*')
      ->from('Panoramica p')
      ->innerJoin('p.Exposicion e')
      ->where('p.id_sala = ?',$id_sala)
      ->orderBy('e.nombre ASC');
*/
    $q = Doctrine_query::create()
      ->select('e.*')
      ->from('Exposicion e')
      ->innerJoin('e.Panoramica p WITH p.id_sala = ?', $id_sala)
      ->orderBy('e.nombre ASC');    
    
    return $q->execute();
    }
}